import { pool } from "../db/pool";

export interface Plan {
  key: string;
  prefix: string;
  label: string;
  durationLabel: string;
  chipLabel: string;
  profile: string;
  bytesLimit: number | null;
  durationDays: number;
  sharedUsers: number;
  priceKobo: number;
  active: boolean;
}

function mapRow(row: any): Plan {
  return {
    key: row.key,
    prefix: row.prefix,
    label: row.label,
    durationLabel: row.duration_label,
    chipLabel: row.chip_label,
    profile: row.profile,
    bytesLimit: row.bytes_limit === null ? null : Number(row.bytes_limit),
    durationDays: row.duration_days,
    sharedUsers: row.shared_users,
    priceKobo: Number(row.price_kobo),
    active: row.active,
  };
}

export async function listPlans(): Promise<Plan[]> {
  const { rows } = await pool.query(
    "SELECT * FROM plans WHERE active = true ORDER BY duration_days ASC, price_kobo ASC",
  );
  return rows.map(mapRow);
}

export async function getPlan(key: string): Promise<Plan | null> {
  const { rows } = await pool.query("SELECT * FROM plans WHERE key = $1", [key]);
  return rows.length ? mapRow(rows[0]) : null;
}

/**
 * Fixes audit finding #2 from the original static-portal review: pricing and
 * plan display data used to live only in login.html's hardcoded HTML, outside
 * plan-data.js's "single source of truth" — so it could silently drift from
 * the router-enforced values. This function generates a plan-data.js file
 * FROM the database, for the router's own static pages (login.html /
 * status.html) to load, closing that gap for good.
 */
export async function exportPlanDataJs(): Promise<string> {
  const plans = await listPlans();
  const entries = plans
    .map((p) => {
      const bytesLimit = p.bytesLimit === null ? "null" : p.bytesLimit;
      return `  ${JSON.stringify(p.key)}: {
    prefix: ${JSON.stringify(p.prefix)},
    label: ${JSON.stringify(p.label)},
    duration: ${JSON.stringify(p.durationLabel)},
    chipLabel: ${JSON.stringify(p.chipLabel)},
    profile: ${JSON.stringify(p.profile)},
    bytesLimit: ${bytesLimit},
    durationDays: ${p.durationDays},
    sharedUsers: ${p.sharedUsers},
    priceNaira: ${Math.round(p.priceKobo / 100)},
  }`;
    })
    .join(",\n");

  return `// AUTO-GENERATED by backend/src/services/planService.ts — do not hand-edit.
// Source of truth is now the "plans" table in Postgres, not this file.
// Regenerate via GET /api/plans/export.js and redeploy to the router's
// /hotspot/ directory whenever a plan changes.
const MOPDATEC_PLANS = {
${entries},
};
`;
}
