// AUTO-GENERATED by backend/src/services/planService.ts -> exportPlanDataJs().
// Source of truth is the "plans" table in Postgres, not this file.
// Regenerate whenever a plan/price changes:
//   curl -H "Authorization: Bearer <admin-token>" https://api.mopdatecwifi.com/api/plans/export.js
// then re-upload the result to the router's /hotspot/ directory next to login.html.
//
// This checked-in copy mirrors database/schema.sql's plan seed data so a
// fresh router has working plan chips before the first regenerate.
const MOPDATEC_PLANS = {
  "LS": {
    prefix: "LS-",
    label: "Low Standard (3GB)",
    duration: "1 Day Validity",
    chipLabel: "Low Standard (3GB - 1 Day)",
    profile: "LS",
    bytesLimit: 3000000000,
    durationDays: 1,
    sharedUsers: 1,
    priceNaira: 500,
  },
  "standard": {
    prefix: "ST-",
    label: "Standard (6.5GB)",
    duration: "1 Day Validity",
    chipLabel: "Standard (6.5GB - 1 Day)",
    profile: "standard",
    bytesLimit: 6500000000,
    durationDays: 1,
    sharedUsers: 1,
    priceNaira: 1000,
  },
  "Trader Pass": {
    prefix: "TP-",
    label: "Trader Pass (18.5GB)",
    duration: "3 Days Validity",
    chipLabel: "Trader Pass (18.5GB - 3 Days)",
    profile: "Trader Pass",
    bytesLimit: 18500000000,
    durationDays: 3,
    sharedUsers: 1,
    priceNaira: 3000,
  },
  "Pro Weekly": {
    prefix: "PW-",
    label: "Pro Weekly (70GB)",
    duration: "7 Days (2 Users)",
    chipLabel: "Pro Weekly (70GB - 7 Days)",
    profile: "Pro Weekly",
    bytesLimit: 70000000000,
    durationDays: 7,
    sharedUsers: 2,
    priceNaira: 5000,
  },
  "Pro Monthly": {
    prefix: "PM-",
    label: "Pro Monthly (150GB)",
    duration: "30 Days (3 Users)",
    chipLabel: "Pro Monthly (150GB - 30 Days)",
    profile: "Pro Monthly",
    bytesLimit: 150000000000,
    durationDays: 30,
    sharedUsers: 3,
    priceNaira: 20000,
  },
  "Premium": {
    prefix: "PR-",
    label: "Premium (Unlimited)",
    duration: "30 Days (5 Users)",
    chipLabel: "Premium Unlimited (30 Days)",
    profile: "Premium",
    bytesLimit: null,
    durationDays: 30,
    sharedUsers: 5,
    priceNaira: 40000,
  },
};
